version: "3.9"

services:
  prod_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo-prod:/etc/mongo
  
  prod_server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod

    ports:
      - "4000:4000"
    
    env_file:
      - ./server/.env

    depends_on:
      - prod_db
  
  prod_client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod

    ports:
      - "3000:3000"

    depends_on:
      - prod_server