version: "3.9"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo:/etc/mongo
    
  server: 
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - db
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - /app/.next
    depends_on:
      - server